### ISSUE TITLE
index.qmd

### ISSUE THREAD

**Issue by ratnanil** [666Xiao666/CMA_Semesterproject_24FS#1]
Is there a reason that you are not working in [index.qmd](https://github.com/666Xiao666/CMA_Semesterproject_24FS/blob/main/index.qmd), but rather [GEO880_Report.qmd](https://github.com/666Xiao666/CMA_Semesterproject_24FS/blob/main/GEO880_Report.qmd)? Did you see these following instructions? 

https://computationalmovementanalysis.github.io/Semester-Project/

**Comment by 666Xiao666** [comment]
> Is there a reason that you are not working in [index.qmd](https://github.com/666Xiao666/CMA_Semesterproject_24FS/blob/main/index.qmd), but rather [GEO880_Report.qmd](https://github.com/666Xiao666/CMA_Semesterproject_24FS/blob/main/GEO880_Report.qmd)? Did you see these following instructions?
> 
> https://computationalmovementanalysis.github.io/Semester-Project/

Hi Nils, thanks for reminding. The reason is GEO_Report.qmd is a drafted version (you can see it's messy inside). I will alter to index.qmd later. Sorry for this mistake.
